### ISSUE TITLE
Cheating programmers?

### ISSUE THREAD

**Issue by master255** [android/architecture-samples#1014]
Why should programmers use your blank project to get started? [And not mine?](https://github.com/master255/blankproject) Because mine is much simpler and more flexible. It has much more features and performance than yours! Why are you scamming everyone?

And where is the fair competition of start- up projects? I think my project is the best! And I can prove it! In fact, you dictate to everyone how to program. That's fascism!

**Comment by JoseAlcerreca** [comment]
![image](https://github.com/user-attachments/assets/f6260bfb-ce9d-4bc8-8bc3-cb317de079d0)

**Comment by master255** [comment]
You fascists!
