### ISSUE TITLE
Push events in the data layer to the presentation layer?

### ISSUE THREAD

**Issue by waleedsarwar86** [android/architecture-samples#106]
What about update events in the data layer and how to notify about them the presentation layer? Let's suppose, that some third party service has updated some user data in the database.

Is event bus approach good for that?
For example, we will define some event class in the domain layer: `UserUpdatedEvent`. Some presenter in the presentation can subscribe/unsubscribe for this event on the event bus. Data layer can post the `UserUpdatedEvent` on event bus.

**Comment by jacquesgiraudel** [comment]
I think the synchronization mechanism between LiveData and Room should permit to do that.

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
