### ISSUE TITLE
Todo-mvp. View is always gone.

### ISSUE THREAD

**Issue by NikitaKozlov** [android/architecture-samples#111]
In `TasksFragment` `mNoTaskAddView` is always gone, because third arguments in `TasksFragment#showNoTasksViews()` is always `false`.
Second problem about it: `OnClickListenter` for `mNoTaskAddView` calls `showAddTask` directly without talking to presenter.

**Comment by JoseAlcerreca** [comment]
Not sure what you mean but after looking at it, looks like mNoTasks is VISIBLE by default and only GONE after the methods are called. Am I missing something?

With the second problem, I agree it should talk to the presenter.

**Comment by NikitaKozlov** [comment]
True, it is visible, by default, but we are setting its visibility manually every time. I will try to explain.

After loading tasks `TasksPresenter#processTasks()` method is called.

1. If `tasks` isn't empty, then `TasksFragment#mNoTasksView` visibility sets to GONE, `TasksFragment#mNoTaskAddView` is a child of that view so it is gone as well.
2. If `tasks` is empty, then `TasksPresenter#processEmptyTasks()` is called, that ends up with calling `TasksFragment#showNoActiveTasks()`, `TasksFragment#showNoCompletedTasks()` or `TasksFragment#showNoTasks()`. All three of them are calling `TasksFragment#showNoTasksViews()` with third argument `false`. This argument is called `showAddView` and is used here: `mNoTaskAddView.setVisibility(showAddView ? View.VISIBLE : View.GONE);`

Probably this view will visible if loading error will occur, but is it intentionally so? You have a FAB that is doing the very same thing.

**Comment by JoseAlcerreca** [comment]
You are right! It used to have a call to action. I don't know what the plan was, I guess it should be true from showNoTasks() and false otherwise. I'll ask UX.

**Comment by NikitaKozlov** [comment]
Or removed, since there is a FAB.

**Comment by Elisey93** [comment]
On second question, seems like mNoTasksAddView's click listener still calling showAddTask() directly, without Presenter

`mNoTaskAddView.setOnClickListener(__ -> showAddTask());`

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
