### ISSUE TITLE
Sample MVP with Clean Architecture and Dagger2?

### ISSUE THREAD

**Issue by funyoung** [android/architecture-samples#121]
I was finish about working on an example  [Clean Dagger2](https://github.com/AndroidClasses/android-architecture/tree/todo-mvp-clean-dagger). MVP + Clean Architecuture + Dagger2, which combines mvp-clean to mvp-dagger2, and I wonder if there was an existing example?

**Comment by JoseAlcerreca** [comment]
Hey funyoung,

Are you asking if we already have mvp-clean-dagger? We don't, although it's a highly requested sample!

Do you want us to review it and put it under "external samples" for now? 

Looks like you based it on the dagger sample and then incorporated the interactors and the rest of the Clean stuff. Did you merge it with the existing Clean branch or did you implement your own version?

**Comment by funyoung** [comment]
Hello JoseAlcerreca,

I am so exciting to hear that mvp-clean-dagger is a highly requested sample.

I think my code is ready for your review and I'd like to know if it was able to be put under "external samples".

You are right, I based it on the dagger sample, and manually move the interactors and the some others code from the Clean stuff, and then I change all the code of dependency injected with Dagger2.

What should I do next for you to review it and put it under "external samples" then?

**Comment by JoseAlcerreca** [comment]
Hey funyoung, can you create a PR in your repo so we can review and add comments?

**Comment by funyoung** [comment]
Hi JoseAlcerreca, I created a PR and signed CLA.

**Comment by mspmax** [comment]
Hi @funyoung, I'm really keen on looking at the design of your code as I have done something similar as well. Is your branch official now in external samples ?

**Comment by funyoung** [comment]
@mspmax I thought the code is ready, but the PR was reject as old one.

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
