### ISSUE TITLE
how to handler the view reference in the presenter if the Activity destroy

### ISSUE THREAD

**Issue by spmonk** [android/architecture-samples#124]
when the `Presenter` is fetching data in the background, the `Activity` destroyed. Does the `IView` reference hold by the `Presenter` need to remove?

**Comment by mawenge** [comment]
set the presenter reference null in onDestroy() method, and safely use View reference in Presenter in case of null object exception

**Comment by Rainer-Lang** [comment]
@JoseAlcerreca Do you think it would be good to catch this possible error and add a solution to these blueprints?

**Comment by StanleyDing** [comment]
@mawenge, why does setting presenter reference solve this problem?

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
