### ISSUE TITLE
[todo-mvp-rxhub] NEW external example using RxHub

### ISSUE THREAD

**Issue by djodjoni** [android/architecture-samples#163]
an external example using [RxHub](https://github.com/apptik/rxHub) which will be basically more data/action event driven and decouple components even more.

it will be based on the todo-mvp-rxjava where P still coordinates V, however M is more decoupled from P maintaining contract only on data types passed back and forth.

**Comment by Rainer-Lang** [comment]
@djodjoni I'm very interested in this example, but if possible cleanarchitecture and dagger...

**Comment by djodjoni** [comment]
thx for the support :)
for the first example ill do it simple with less changes as to be comparable. However then ill add others definitely with dagger, real network (like [jus](https://github.com/apptik/jus) as it is mine :), more test examples with BDD using cucumber and so on. 

About Uncle's bob clean architecture there is too much fuss about it however we've been using it for a long time as multi-layered or multi-tier(used for physical separated layers mostly). MVP, MVVM are essentially 3-layered you can achieve the so called used-cases by simply splitting P into ViewP and BizP and go on with separation as needed. However these separations IMO come naturally as the code grows, but the UseCase interfaces and classes used in the most projects including this one are a pile of boilerplate, where biz code is probably 1/10 of the code surrounding it. 

So no, I wont use the 'UseCases' as in the example branch in this project, but anybody could fork and separate them as they wish :)

**Comment by Rainer-Lang** [comment]
I'm very interested :)
I didn't know "jus", thanks!

I'm not married with CleanArchitecture.

If possible and if you have time - just make your BIG example. :) :+1:

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
