### ISSUE TITLE
[todo-mvp-loaders] multiple background tasks for single presenter

### ISSUE THREAD

**Issue by pavelshackih** [android/architecture-samples#164]
Hello, folks!
Could you please extend example with `TasksPresenter` when it has multiple background tasks.
For example: in current version it supports clearing completed task, what if clear should call network request? In this case, you create a separate loader? What if they should be combined into a chain?

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
