### ISSUE TITLE
[todo-mvp-clean]TasksRepository is not thread-safe

### ISSUE THREAD

**Issue by kmfish** [android/architecture-samples#179]
UseCase.exceuteUseCase() run in a thread pool, so should synchronized the visit of shared resource (e.g., TasksRepository.mCacheTasks)

**Comment by JoseAlcerreca** [comment]
@flipper83 please have a look.

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
