### ISSUE TITLE
New sample: MVP-RxJava-Dagger2

### ISSUE THREAD

**Issue by Rainer-Lang** [android/architecture-samples#21]
Like mentioned in #9 this sample will come after RxJava and Dagger2 sample.

**Comment by HugoCastro** [comment]
May I suggest MVP-Clean-RxJava-Dagger2 after that.

**Comment by Rainer-Lang** [comment]
@HugoCastro This would be really really interesting.

**Comment by Rainer-Lang** [comment]
@HugoCastro You could make an issue (request).

**Comment by JoseAlcerreca** [comment]
We could generate all the permutations of tools and architecture patterns but that would be a maintenance hell :) As these are not templates, but learning material, we should keep the number of samples low. That said, we encourage people to fork and release in a different repo. We'll create an unofficial list of variants if this happens.

**Comment by Rainer-Lang** [comment]
@JoseAlcerreca If I understand you correct, you will maintain these blueprints in this project?! This are really fantastic news!
Therefore you don't want create "all" architecture patterns - and suggest that the community makes the others (and you link to them from this project).
I only want to be secure that I understand you. :)

But as a suggestion - would it be possible to make the "architecture pattern requests" here in this project (so everybody can see and grab it for a new project)? You could tag this issue with eg "New sample request - community". What do you think?

**Comment by JoseAlcerreca** [comment]
Well, I won't maintain them alone, we have a group of core contributors :+1: 

And yes, the requests from the community are tagged as "New sample request" and the planned samples are tagged as "New sample".

**Comment by Rainer-Lang** [comment]
Sorry, of course you and all the other contributors. Thanks to these guys!

I don't think that most people could understand the difference between "New sample request" and "New sample"....

**Comment by JoseAlcerreca** [comment]
Done.

**Comment by dyguests** [comment]
Lol!!!!,This is what I waiting for!!!!!!!!!

**Comment by Rainer-Lang** [comment]
@dyguests What exactly do you mean with "this"? ;)

**Comment by dyguests** [comment]
@Rainer-Lang ,I mean "New sample: MVP-RxJava-Dagger2".
I try to learn dagger2 for times.but now I know how to use dagger(a little),do't know why sue dagger.
It still have long time to learn it.:)

**Comment by Rainer-Lang** [comment]
@dyguests I'm thinking about to make this example... But I couldn't promise anything.

**Comment by lmz1993** [comment]
I  LOVE YOU AND MVP

**Comment by quchwe** [comment]
dagger-rx-retrofit-mvp

**Comment by andrewpiggy** [comment]
+1 @quchwe, Dagger2 + RxAndroid + Retrofit + MVP are my dream combination.

**Comment by tunjid** [comment]
Closing as obsolete.
