### ISSUE TITLE
New sample: DataBinding library and RxJava

### ISSUE THREAD

**Issue by elirex** [android/architecture-samples#214]
I'm thinking about doing a sample that uses Data Binding library and RxJava.
What do you think?

**Comment by Rainer-Lang** [comment]
👍

**Comment by JoseAlcerreca** [comment]
Ideally that sample would be a merge between the data binding and the rxjava samples. Is that your plan?

**Comment by elirex** [comment]
I'm just simply merging the two branches (todo-databinding and todo-mvp-rxjava).
The repo is here: [https://github.com/elirex/android-architecture](https://github.com/elirex/android-architecture).
#### TODO:
* Refactor the "addedittask" and "taskdetails" to the data binding.

**Comment by JoseAlcerreca** [comment]
Cool, let us know when finished.

**Comment by elirex** [comment]
## Update progress

### Done:
At [70bf0bb](https://github.com/googlesamples/android-architecture/commit/70bf0bb1826a38f56acedff0e35c748bb6e95111) and [e43ade6](https://github.com/googlesamples/android-architecture/commit/e43ade61ac4cc253636bd60a9d296ef76213a3c5) commit uses RxJava and SqlBrite to refactor the data repository and this part implementation is mainly being referred to [todo-mvp-rxjava](https://github.com/googlesamples/android-architecture/tree/todo-mvp-rxjava).

Commit [b5d992d](https://github.com/googlesamples/android-architecture/commit/b5d992d5aa05a201c90fd2bac4fe7f0831740663), [78c5524](https://github.com/googlesamples/android-architecture/commit/78c552478b2787e132640928829b4dc47b57be5c), [6e0bc92](https://github.com/googlesamples/android-architecture/commit/4c8fb49a15863597076e2c436f738839df5363c4), [4c8fb49](https://github.com/googlesamples/android-architecture/commit/96e4858e1c0ff480fede51ac393c78f2760027f4), [96e4858](https://github.com/googlesamples/android-architecture/commit/7302e97c397a0d1e5afb270a58dcc41d61953fd5), [7302e97](), and [b478445](https://github.com/googlesamples/android-architecture/commit/b478445c93bcd1f21138496ac9dfadef0c25150f) uses Data-Binding to refactor [tasks](https://github.com/elirex/android-architecture/tree/dev-todo-databinding-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks), [taskdetail](https://github.com/elirex/android-architecture/tree/dev-todo-databinding-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/taskdetail) and [statistics](https://github.com/elirex/android-architecture/tree/dev-todo-databinding-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics).

[839b944](https://github.com/googlesamples/android-architecture/commit/839b944a2f9c529b1e5cc7b9d9f9af9205618bf0), [e20fd61](https://github.com/googlesamples/android-architecture/commit/e20fd61e21857f295f546dd7377a699bb8fd060f), [30febcf](https://github.com/googlesamples/android-architecture/commit/30febcf8f6de6d7728f4d22a2bde5336581013da) and [5ad9500](https://github.com/googlesamples/android-architecture/commit/5ad9500459f01bf8562a7d94c0b1fe487a00723b) update all tast tasks to comply with the current architecture.

### TODO:
* Refactors [addedittask](https://github.com/elirex/android-architecture/tree/dev-todo-databinding-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask).
* Updates README

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
