### ISSUE TITLE
Yeoman Generator for Android Architecture 

### ISSUE THREAD

**Issue by ravidsrk** [android/architecture-samples#216]
I created Yeomon generator to create apps using any of these architectures. https://github.com/ravidsrk/generator-android-architecture

I also have the node script to sync changes which happens on all branches. https://github.com/ravidsrk/generator-android-architecture/blob/master/generators/app/sync_templates.js

**Comment by JoseAlcerreca** [comment]
Thanks, not sure how useful this is though. This project is not meant to be used a template so if we add it to the README it will send the wrong message...

**Comment by JoseAlcerreca** [comment]
Does it check out the different branches or does it do something fancier?

**Comment by ravidsrk** [comment]
@JoseAlcerreca Its doesn't just checkout different branches. It does lot more than checkout. You can create a new app using one the todo architecture user wants. e.g. app name, package can be changed. 
<img width="1440" alt="screen shot 2016-10-26 at 7 11 20 pm" src="https://cloud.githubusercontent.com/assets/529352/19728219/3480d816-9bb0-11e6-87f8-e10032598942.png">
<img width="1440" alt="screen shot 2016-10-26 at 7 11 34 pm" src="https://cloud.githubusercontent.com/assets/529352/19728217/347c5c00-9bb0-11e6-9577-a376d57628ea.png">
<img width="1440" alt="screen shot 2016-10-26 at 7 11 51 pm" src="https://cloud.githubusercontent.com/assets/529352/19728218/347f8254-9bb0-11e6-9a64-ce4c1b553b87.png">

**Comment by ravidsrk** [comment]
@JoseAlcerreca Did you get a chance to check above?

**Comment by ravidsrk** [comment]
@JoseAlcerreca I have recored the video explaining how yeoman generator. Please have a look.
![yly1xy0f2n](https://cloud.githubusercontent.com/assets/529352/22735516/06276292-ee20-11e6-9bd3-d72668b03868.gif)

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [architecture templates](https://github.com/android/architecture-templates).
