### ISSUE TITLE
New Sample: Demonstrate architecture benefits by replacing current datasources with Firebase RTDB

### ISSUE THREAD

**Issue by remcomokveld** [android/architecture-samples#227]
Since a good architecture serves to make it easy to swap implementations I think it would be nice to have one or more samples which demonstrate how a data source implementation using a combination of a remote api, and a local sqlite database can be replaced with a realtime database.

I am not sure yet how it would be possible to run the same espresso tests in such a sample since mocking the firebase components is probably hard, but it would be, both a nice display of the flexibility of the current architectures as well as a nice example of how you can abstract firebase specific implementations away from the ui. 

[Here](https://gist.github.com/remcomokveld/09b111e54dfc9cd8c0fc9a4d9c3bd63b) is an idea I had recently for using loaders with Firebasre RTDB, although this is just a sample and I have not yet used it in a real scenario it might be an inspiration for this sample

**Comment by antipochkin** [comment]
Maybe I misunderstood the concept and you can clarify it to me. I am using this architecture and firebase for my RemoteDataSource(RxFirebase library), the idea of using Firebase as a RemoteDataSource and not the only datasource is  to observe the local tables and not the remote tables (when one shared table among several activities  changed , all activities are notified).
If firebase stores its own local db and I can use firebase as the only datasource(can I?) how does your example fits the architecture?

**Comment by Nominalista** [comment]
Anybody who can share experience by combining Firebase and (I understand it's best way, correct me if I'm wrong) mvp-loaders?

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
