### ISSUE TITLE
[todo-mvp-clean] TasksPresenterTest interact with repository instead of use case?

### ISSUE THREAD

**Issue by DangOnGitHub** [android/architecture-samples#255]
Why do tests in `TasksPresenterTest` such as the test `loadAllTasksFromRepositoryAndLoadIntoView` interact with `TasksRepository`? Shouldn't presenter know the abstraction behind use case?

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
