### ISSUE TITLE
New sample: MVC

### ISSUE THREAD

**Issue by juanyanezgc** [android/architecture-samples#31]
Hi guys, I'd like to contribute with a MVC and MVC-Dagger2 architecture sample. It would be something similar to what I used in this project https://github.com/Smart-Studio/device-info/tree/develop. Let me know your thoughts.

**Comment by Rainer-Lang** [comment]
Please have a look here: MVP-Clean-RxJava-Dagger2

> JoseAlcerreca: We could generate all the permutations of tools and architecture patterns but that would be a maintenance hell :) As these are not templates, but learning material, we should keep the number of samples low. That said, we encourage people to fork and release in a different repo. We'll create an unofficial list of variants if this happens.

**Comment by JoseAlcerreca** [comment]
In this case we're very interested in exploring MVC, since we're only talking about MVP so far. Do you have a blog post or something to go with that code @juanyanezgc?

**Comment by juanyanezgc** [comment]
@JoseAlcerreca I'm afraid I don't have anything at the moment.Actually I was thinking about contributing by using MVC on the TODO app but maybe I could put something together over the weekend to explain the code of that project first if you think is worth it

**Comment by JoseAlcerreca** [comment]
I think that would be the way to go yep!

**Comment by JoseAlcerreca** [comment]
I've edited the issue title, Dagger2 would have to come after this one.

**Comment by TwentySevenC** [comment]
This would be great!!

**Comment by geniushkg** [comment]
@JoseAlcerreca, Since no one had contributed to MVC Sample, I am starting out today with it, by this weekend, will update with code and a companion blog post.

First I would start with very basic MVC without any external libraries, then would upgrade it further as already mentioned above.

**Comment by geniushkg** [comment]
Sorry, guys no update yet.

**Comment by tunjid** [comment]
Closing as obsolete.
