### ISSUE TITLE
[todo-clean-rxjava-dagger-kotlin] All togheter proposal for learning purposes

### ISSUE THREAD

**Issue by Ndrocchietto** [android/architecture-samples#333]
According to my experience the above mentioned architecture is the one  most used at the moment.  This architecture repository is great but could be useful to see all the hot tools together, to give to who is  learning a real life feeling on how a project with good architecture is expected to appear, how is tested. Instead of all the fragmented sections, that also have an huge learning value can i suggest to start a todo  clean+rxjava2 project and then on a second moment incrementally adding Dagger and Kotlin?

I would be eager to participate on that, but apart the guidelines mentioned when i submitted this "issue" I do not know if I can push incremental commits, hoping to be helped/reviewed by the community, or if I should just consign the project all in one, this would be a bit painful because I am not at such an advanced coding level, even if this one is more a patchwork job because almost all the single implementations are already working.

The proposed plan would be starting from the clean project and add RXJava, then on a second moment Dagger, and at end do it on two flavors Kotlin and Normal

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
