### ISSUE TITLE
[todo-mvp-rxjava] TaskRepository doesn't query network if local storage is unavailable

### ISSUE THREAD

**Issue by shubham1g5** [android/architecture-samples#334]
In `todo-mvo-rxjava` sample, inside `TaskRepository.getTasks()` function we do

```
// Query the local storage if available. If not, query the network.
return Observable.concat(localTasks, remoteTasks)
                    .filter(tasks -> !tasks.isEmpty())
                    .first();
```

Now `Observable.concat` only fires up the later observable after the first one completes. For us `localTasks` never completes and is always waiting for `onNext` events to happen. So in this case `remoteTasks` will never get fired up and in the case when we have `localTasks` emit empty tasks list, observable returned by the above statement will never emit any event to it's subscribers.

**Comment by andrewclam1991** [comment]
I seem to have the same problem as mentioned with this example. @shubham1g5 Any suggestion/fix on the remedy?

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
