### ISSUE TITLE
[todo-mvp-clean] Crashed when activity is destroyed.

### ISSUE THREAD

**Issue by thaihuynhxyz** [android/architecture-samples#361]
I turn on "Don't keep activities" flag to simulate activity destroyed by system when we leave it.
In SaveTask i put `Thread.sleep(2000);` before `getUseCaseCallback().onSuccess(new ResponseValue(task));`
My step is:
add new task -> save -> press home button to put app to background -> after usecase done callback in presenter `mAddTaskView.showTasksList();` and in fragment `getActivity().setResult(Activity.RESULT_OK);` will crash because `getActivity()` = null
How do I handle this case?

**Comment by JoseAlcerreca** [comment]
Good catch, seems like todo-mvp-clean has a couple of leaks already.

A normal `if (getActivity() != null || !getActivity().isFinishing())` would suffice in this case.

**Comment by thaihuynhxyz** [comment]
If we add this check we cannot finish activity as expected

**Comment by JoseAlcerreca** [comment]
In that case before calling the fragment you can check if fragment.isActive().

Actually, I think this should be done in 
https://github.com/googlesamples/android-architecture/blob/todo-mvp-clean/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskPresenter.java#L134

As you see, every call to the view is protected by View.isActive(). Except those ones.

**Comment by thaihuynhxyz** [comment]
In my case that I mentioned: 
- I've assumed SaveTask useCase take long time in background thread.
- While task run on background thread view is destroyed (I simulated by leave app to background with dontKeepActivityFlag in setting).
- After SaveTask useCase done successfully (app still on background and !fragment.isActive()), we need finish activity to navigate to prevScreen.
So:
- If we don't check fragment.isActive() app will crash.
- If we check fragment.isActive(). How we can finish activity as expected?

**Comment by JoseAlcerreca** [comment]
Why do you want to finish an activity that is killed by the system?

**Comment by thaihuynhxyz** [comment]
If I pressed save, then press home to leave app to background. SaveTask useCase is executed successfully. then I comeback and activity is reCreated but nothing happened, I still in screen createTask although task is saved to database. I press create again I have two tasks.

**Comment by JoseAlcerreca** [comment]
Yeah that makes sense. I'll write it down although I'm not sure if it complicates the sample too much.

In principle I would use onSaveInstanceState to persist whether the activity is done or not and check it in onCreate.

**Comment by SbyXlmm** [comment]
google  gooogle google

**Comment by SbyXlmm** [comment]
i love google

**Comment by SbyXlmm** [comment]
google all product i like

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
