### ISSUE TITLE
[todo-mvp-dagger] clean up Is Data Missing Logic

### ISSUE THREAD

**Issue by digitalbuddha** [android/architecture-samples#381]
Currently we are using 2 variables to maintain mIsDataMissing within `AddEditPresenter`, we should clean up the code to only need a single state variable.

**Comment by JoseAlcerreca** [comment]
Right now it's only visible here:
https://github.com/digitalbuddha/android-architecture/pull/3

**Comment by digitalbuddha** [comment]
If we move restoreState to above super.onCreate() we can guarantee to always have our value injectable without the need of a lazy in presenter.

**Comment by JoseAlcerreca** [comment]
@digitalbuddha did you adddress this?

**Comment by tunjid** [comment]
todo-mvp-dagger is no longer maintained
