### ISSUE TITLE
New sample: Redux

### ISSUE THREAD

**Issue by mortyccp** [android/architecture-samples#46]

**Comment by kmdupr33** [comment]
Is anyone working on this? If not, I'd like to make it happen.

**Comment by initialjie** [comment]
Redux is based on "Flux" which is very different  from "MVP".

**Comment by wiyarmir** [comment]
@initialjie the repository is named `android-architecture`, not `android-architecture-mvp` anyway 😄

**Comment by JoseAlcerreca** [comment]
@kmdupr33 sorry I missed this, please feel free to start and have a look at https://github.com/googlesamples/android-architecture/wiki/External-samples

**Comment by mndarren** [comment]
Got it. Thx.

Darren



mndarren@gmail.com
 
From: Jose Alcérreca
Date: 2016-07-20 12:00
To: googlesamples/android-architecture
Subject: Re: [googlesamples/android-architecture] New sample: Redux (#46)
@kmdupr33 sorry I missed this, please feel free to start and have a look at https://github.com/googlesamples/android-architecture/wiki/External-samples

**Comment by Takhion** [comment]
I may actually do this if I find the time; I've written a Redux port and I want to test it in a sample app

**Comment by tunjid** [comment]
Closing as obsolete.
