### ISSUE TITLE
[todo-mvp] Task model object's equals()/hashcode() broken

### ISSUE THREAD

**Issue by dsyang** [android/architecture-samples#478]
Is there a reason why Task#equals() and hashcode() do not take into account the completed boolean? 

https://github.com/googlesamples/android-architecture/blob/30f7c5a16bb0854e003530e81403e922e745d311/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/Task.java#L144-L151

**Comment by tunjid** [comment]
todo-mvp is no longer maintained
