### ISSUE TITLE
[todo-mvp-clean] Possible memory leak in use case callback

### ISSUE THREAD

**Issue by tylersuehr7** [android/architecture-samples#489]
**Summary**
A memory leak will occur if executing a long-running use case, that references the presenter's view in the callback of the use case (anonymous inner-class), and the implementation of the view (Activity/Fragment/View)'s lifecycle has ended before the completion of the use case.

This memory leak is not prominent when executing use cases that use a local SQLite database (in this project's examples), but it is very prominent when executing use cases that utilize the network or perform a long-running task and return data in the use case callback.

**Discovery**
I had discovered this issue when I was using this architecture style on an example application. I was trying to remove a Fragment from an Activity, by pressing the back button on the navigation bar, after I had scheduled a long-running use case (performing network and cache operations) to execute before it had finished executing and triggering the use case callbacks.

**Example (for replication)**
Specifically, I had created a use case that performed a network I/O operation, buffered the stream into a string, parsed data from the string into a model, and then cached the model in a local SQLite database before calling back to the presenter with the model. 

I implemented the MVP view on a Fragment that was then shown in an Activity, but also added to the back stack in the FragmentManager. When I executed the use case, by pressing a button in the Fragment's view, I then pressed the back button on that navigation bar to go back and remove the Fragment from the Activity.

After another second or two (depending on network latency), it crashed the application because the use case tried to call back to an anonymous inner-class that was created in the presenter of the view (implemented by the Fragment), that was created when the use case was scheduled to execute, and had its lifecycle ended because it was removed from the screen when I had pressed back on the navigation bar. 

This leaked memory because the use case's callback (anonymous inner-class), created by the presenter when scheduling use case execution, referenced the view (implemented by the Fragment), therefore not allowing the GC to recycle the Fragment when its lifecycle had ended after I had pressed back on the navigation bar.

**Side notes**
I think I have found a solution to this issue that doesn't 'break' MVP architecture guidelines/rules. I can also attach log information with the exception's stack trace if needed.

**Comment by shiehnpin** [comment]
I was wondering callback can be canceled by expose UseCaseScheduler.remove(Runnable) method?

**Comment by tunjid** [comment]
Closing as obsolete in the context of the [current architecture guide](https://developer.android.com/topic/architecture).
