### ISSUE TITLE
Presenter - Binding with View

### ISSUE THREAD

**Issue by gvaish** [android/architecture-samples#50]
The `Presenter` is just _created_ and code like [this in the activity](https://github.com/googlesamples/android-architecture/blob/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskActivity.java#L73-L76) looks pretty lame although meaningful work happens in the [presenter constructor](https://github.com/googlesamples/android-architecture/blob/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskPresenter.java#L50-L57)

Proposal:

Introduce a method `bind` in the `Presenter`.

So, the code in presenter class will be:

``` java
class ddEditTaskPresenter implements
        AddEditTaskContract.Presenter,
        TasksDataSource.GetTaskCallback {

  Presenter(...) {
    this.blah = checkNotNull(blah);
    ...
  }

  bind() {
    mAddTaskView.setPresenter(this);
  }

}
```

and the activity will be:

``` java

class AddEditTaskActivity {
   onCreate(...) {
      ....
      presenter = new AddEditTaskPresenter(....);
      //wherever required...
      presenter.bind();
   }
}
```

Thoughts?

**Comment by JoseAlcerreca** [comment]
Hi, thanks for your suggestion but, please, read:
https://github.com/googlesamples/android-architecture/blob/master/code-of-conduct.md

**Comment by gvaish** [comment]
Sure @JoseAlcerreca 

I am not sure of the context - what specific section, if any, you want me to read. Or is it more of FYI. :-)

**Comment by JoseAlcerreca** [comment]
We want people to contribute to this project understanding that their mistakes will be fixed, but knowing that their work will be respected. I'm sure you meant "improvable" when you said "lame" :)

I agree with you though, this is not a good practice. However, I prefer a factory method. Agreed?

**Comment by JoseAlcerreca** [comment]
Ping!

**Comment by gvaish** [comment]
Missed the earlier ping.

Lame = Looks lame & improvable.

And yes - factories are good indirections to start with. I prefer to use service locator pattern than raw factories.
Or even better - use dependency injection.

**Comment by Rainer-Lang** [comment]
@gvaish Want to make a PR? :+1:

**Comment by tunjid** [comment]
Closing as obsolete.
