### ISSUE TITLE
[Request] New sample with Agera

### ISSUE THREAD

**Issue by krysanify** [android/architecture-samples#53]
I'm not sure if this make sense, 'cause the RxJava version is already in progress and both may result in similar codes. Nevertheless, would be interested to see the differences fleshed out.

**Comment by JoseAlcerreca** [comment]
Yes it will make sense but we have to finish the RxJava sample first. It's the industry standard and Agera is not even stable yet.

**Comment by tunjid** [comment]
Closing as obsolete.
