### ISSUE TITLE
GetStatistics UseCase for "todo-mvp-clean"

### ISSUE THREAD

**Issue by NikitaKozlov** [android/architecture-samples#58]
Calculation of the statistics in `StatisticsPresenter` looks more like a domain logic, not a presentation.
Plus `StatisticsPresenter` right now have dependency on `TasksFilterType`, which could be avoided.
My suggestion is to create an additional `UseCase`: `GetStatistics`, which will simplify `StatisticsPresenter`, and make it independent from `tasks` and `data` packages.

I implemented it [here](https://github.com/Kaerdan/android-architecture/blob/add-statistics-use-case/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics/domain/usecase/GetStatistics.java), it is required some polishing, but I hope that idea is clear.

**Comment by flipper83** [comment]
it's ok. I've been reviewing the code and I think calculating statistics is a business requirement, so it's wrong to do it in the presenter. Can you send a PR with your changes?

**Comment by Kaerdan** [comment]
I will check that testing works correctly and send a PR in a few days.

**Comment by yesenarman** [comment]
It looks like this issue has been resolved. Maybe it should be closed?

**Comment by tunjid** [comment]
Closing as obsolete.
