### ISSUE TITLE
Question - dev-todo-mvp-dagger-update

### ISSUE THREAD

**Issue by kdani41** [android/architecture-samples#64]
Hi all,
I have a question regarding the dagger-mvp-update branch.. I am trying to make a sample for rxjava+retrofit +dagger using the beautiful sample that you guys have provided. I saw for each fragment we have a fragment component and a module for that specific view..I really liked this idea but I was just concerned will this be same when i have 1 activity holding 10 fragment or more.. Also I wanted to ask is there any specific reason for starting the presenter cycle from on resume?
Also a huge thanks to you all for putting your efforts in making this beautiful sample👍

**Comment by JoseAlcerreca** [comment]
Check out issue #3, which is about having a tablet layout and multiple fragments per activity. Not done yet though. Presenters need to change somehow. You can create multiple presenters and pass messages between them or create a new presenter for this view.

Specific reason for starting the presenter from onResume vs what? 

Thanks!

**Comment by kdani41** [comment]
Thanks Jose, I will keep following the project to look for any example and will post here if I come up with something.
For presenter what if it's used as a member injection in the fragment and injecting the fragment itself. So, the presenter cycle can start from onCreate. I just wanna know the suggested way or the best practice.

**Comment by ialmetwally** [comment]
I'm also wondering why presenters are not injected into fragments?

**Comment by tunjid** [comment]
Closing as obsolete.
