### ISSUE TITLE
TaskDetailPresenter has null check in GetTask callback for "todo-mvp-clean"

### ISSUE THREAD

**Issue by NikitaKozlov** [android/architecture-samples#65]
`TaskDetailPresenter` shouldn't check for task being null in `GetTask.ResponseValue`, because `GetTask.ResponseValue` has a `@NonNull` annotation in the constructor.
I changed it [here](https://github.com/Kaerdan/android-architecture/blob/563ad4a4613141c28310092f6f5e9654e6765dba/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/taskdetail/TaskDetailPresenter.java). Also I added null check in [GetTask](https://github.com/Kaerdan/android-architecture/blob/563ad4a4613141c28310092f6f5e9654e6765dba/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/domain/usecase/GetTask.java) itself, because potentially `TasksRemoteDataSource` could return null.

**Comment by tunjid** [comment]
Closing as obsolete.
