### ISSUE TITLE
[master] Remove Event.kt file

### ISSUE THREAD

**Issue by raminqaf** [android/architecture-samples#672]
While going through the code and the classes, I have noticed that the [Event.kt](https://github.com/googlesamples/android-architecture/blob/master/app/src/main/java/com/example/android/architecture/blueprints/todoapp/Event.kt) file that wraps the objects into a generic `Event` object is a redundant task. This file makes the code more complicated to understand and does not provide any great value for observing the Live data objects. So in my opinion removing it from the code makes things much simpler. I have already done it in a different branch and just need to push it and create a pull request for review.

**Comment by sergey-ben** [comment]
@raminqaf https://github.com/googlesamples/android-architecture/issues/593

**Comment by dave-kennedy** [comment]
I think the purpose of the Event class is to prevent observers from firing more than once.

On your branch, what happens if the snackbar text is updated and then the device is rotated?

**Comment by JoseAlcerreca** [comment]
https://medium.com/androiddevelopers/livedata-with-snackbar-navigation-and-other-events-the-singleliveevent-case-ac2622673150
