### ISSUE TITLE
how to deal with the view may not be able to handle UI updates anymore

### ISSUE THREAD

**Issue by pangff** [android/architecture-samples#68]
when network api callback, the view may not be able to handle UI updates anymore, how to deal with  and how to check? 
the view holds the presenter instance, presenter holds view instance, and presenter holds data loader instance. so that when network is slow , and user close activity without data loader calling back,the activity instance will not be freed and collected . if user open and close activity  with data loading frequently, in this moment, many activities in memory will not be freed, and the memory use will increase. how to deal with? and what about using SoftReference to view in presenter?

**Comment by waleedsarwar86** [comment]
@pangff Did you find any solution?.

**Comment by pangff** [comment]
@waleedsarwar86 no

**Comment by tunjid** [comment]
Closing as obsolete.
