### ISSUE TITLE
[todo-mvp-clean] does not follow important Clean Architecture principles

### ISSUE THREAD

**Issue by marcosalis** [android/architecture-samples#695]
Let me start by saying this is fully intended as constructive criticism, and I would very much like to start a broader discussion on the topic 😉 
I am extremely grateful to the Android folks for creating and maintaining this samples repository. I think it's an invaluable source of material for developers, especially those who are only getting started with the Android platform.
That said, with "_great power comes great responsibility_". These samples are used by thousands of developers, and in many ways have significantly contributed to shape the architecture of Android applications throughout the past few years (MVP, separation of layers, multi-module).
It is the maintainers responsibility, then, to make sure these samples are correct and not confusing, and actually follow the principles behind the type of architecture they aim to showcase.

I personally don't find this is fully the case with the `todo-mvp-clean` branch.

I believe it is a good starting point for small projects, and a great alternative to the "shove everything in the Fragment/Activity" approach, or even a much better solution for medium/large applications than just using MVP alone.
But Clean Architecture (as described by his creator _Robert C. Martin_ - I really recommend his book on the topic) is much more than creating three Gradle modules for _data/domain/presentation_, and use classes named `Repository` and `UseCase`.

As part of my job, I interview Senior Android developers and give them coding tests quite regularly, and I have to come to terms with the fact that the majority of them think that the above is everything that Clean Architecture is about.
I also sometimes hear Clean Architecture detractors, who state it "doesn't work ™️ " when they really haven't understood it or applied it properly. That makes me sad.

Without getting into much detail, these are the main missing aspects in the sample which are mentioned in the book (or in [this talk](https://www.youtube.com/watch?v=o_TH-Y78tt4) by the author himself) and that are crucial for _Clean_ to work in the real world:
- Full **separation of concerns** (chapter 22). We can identify several layers in Clean: UI (View), Presentation, Business (Use Cases), Entity, Data Access, Data. There is a very specific and strict way that these layers should communicate (i.e. see _page 208_): this, in practice, means in most cases using a separate Gradle module for each.
- **Decoupling layers** (_page 151, and chapters 22-25_). Most of these layers should be strictly separated by layer boundaries (see modules above), and their (Gradle) dependency and relative visibility should be enforced by using `implementation` more often than `api`. We all know that if a class is available at compile time where it shouldn't, it *will be used* 😄 
- The **business layer should not depend on the data layer** (depend upon abstractions, not frameworks) and dependency inversion. There should be a layer, the "Data Access", mainly made of `Repository` interfaces, upon which both "Data" and "Business" depend upon (also mentioned in [#515](https://github.com/android/architecture-samples/issues/515))
- The "Business" layer is made up of **Use Cases** (or Interactors) and **Entities**. These are not the same thing, and they shouldn't belong to the same Gradle module (it is impossible to achieve the two points below otherwise):
    - Use Cases (platform/product dependent rules) depend on the "Data Access" layer
    - Entities (pure business, platform-agnostic rules) should not depend on anything (and ideally should be a Java/Kotlin-only module with no Android dependencies)

There would be much more to it, but those are the main points. I fully agree that depending on the size of a project, the architecture can be flexible and accommodate simplifications, and I'm not extremely dogmatic about this either. But it is also one of the main points of the book that, in order for the architecture to be open and easy to change, the boundaries above are extremely important.

For those interested, [here's a link](https://github.com/Teamwork/android-clean-architecture) to a repository with my Team's approach to using Clean Architecture in (medium/large) Android projects.

**Comment by roel1975** [comment]
Hello, I suppose that those comments are ment for me? I am new here and don't know enough yet how everything works. The reason that I am subscribed is that I really get great help from github (see several mails) for my problem with Google etc. I need protection against the attacks that had been serious consequences. Sincerely. Roel1975 Falcon.

**Comment by JoseAlcerreca** [comment]
That branch is deprecated

**Comment by marcosalis** [comment]
Are there any plans to introduce a new Clean architecture sample then @JoseAlcerreca ?
IMHO it's a type of architecture that would be important to showcase in here.

**Comment by GameplayJDK** [comment]
How is the branch deprecated? There is no notice or anything in the README about that. Well, it hasn't been updated since one year or so, that's true, but doesn't really signal a deprecation here..

I also think mvp-clean is a valuable part to this collection of examples. That sample was very helpful when I started looking into android and software architecture in general one or two years ago.
