### ISSUE TITLE
Not clear why CoroutineScope is used

### ISSUE THREAD

**Issue by daespark** [android/architecture-samples#727]
This have been helpful for me to get started with coroutine for my codebase. However, I find some decisions not making much sense to me. I have 2 questions when I look at 
https://github.com/android/architecture-samples/blob/18be6c67a8afd5341f36fd13cf26b1dcdb8dd15e/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source/DefaultTasksRepository.kt

1. Why are some of the suspend functions using CoroutineScope while others don't? Is there some sort of benefit for this? and how are you deciding it? comments could be helpful :)

2.Also, it is said that room's suspend queries are using it's own thread, and it is better to not make it run on io thread by running with Dispatcher.io. Why does this code contradict that?

Thanks for keeping this sample upto date 👍

**Comment by quiver4arrow** [comment]
They've made these strange decisions with no comments why, in TasksDataSource too.
Not only Kotlin Coroutines are vague enough we have to bear the ambiguity of the code which is suppose to aime beginners and intermediate devs!
