### ISSUE TITLE
[dev-dagger] Current filtering state is lost across process death

### ISSUE THREAD

**Issue by Zhuinden** [android/architecture-samples#731]
In https://github.com/android/architecture-samples/blob/8b028e3dadc8a0faa69d5e9f064befb9abb4dae7/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksViewModel.kt#L64

The current filtering is not preserved in any way across process death, even though that is expected behavior. This was originally also a problem [on master](https://github.com/android/architecture-samples/issues/663).

A possible solution would be to use a `SavedStateHandle` provided to the `ViewModel` from an `AbstractSavedStateViewModelFactory`. 

I would expect this approach to be displayed in an example that is meant to "show how to use AAC ViewModel with Dagger", while still creating an app that works reliably even when it's put to background for a given period of time.

**Comment by rajBopche** [comment]
@Zhuinden Is there any way I can force this process death and observe the issue you are mentioning.
Like using an ADB command or some plugin tool on Android Studio?

**Comment by Zhuinden** [comment]
Following the steps outlined in https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399 should work, although AS 4.0 had some quirkiness where the terminate button behaved differently. In that case, `adb shell am kill packagename`is what works.
