### ISSUE TITLE
How do we inject runtime arguments into the viewmodel?

### ISSUE THREAD

**Issue by CraZyLegenD** [android/architecture-samples#740]
What if we wanted to have runtime arguments or other runtime arguments besides SavedStateHandle?

```
@AndroidEntryPoint
class TasksFragment : Fragment() {

    private val viewModel by viewModels<TasksViewModel>()

    private val args: TasksFragmentArgs by navArgs()

    private val argToInject get() = args.userMessage
....
```

```
class TasksViewModel @ViewModelInject constructor(
    private val tasksRepository: TasksRepository,
    @Assisted argToInject:Int,
    @Assisted private val savedStateHandle: SavedStateHandle
) : ViewModel()
```

`@Assisted argToInject:Int` isn't known to Dagger since we can't annotate argToInject with `@Assisted`, do we still have to use [Assisted Inject by Square](https://github.com/square/AssistedInject) or there's another way?

**Comment by CraZyLegenD** [comment]
@JoseAlcerreca

**Comment by manuelvicnt** [comment]
Can you move this bug to the dagger issues, please? 
https://github.com/google/dagger/issues

Short answer: it's not possible at the moment until AssistedInject is added to Dagger (https://github.com/google/dagger/issues/1825)

**Comment by CraZyLegenD** [comment]
Done, the issue lives on https://github.com/google/dagger/issues/1906
