### ISSUE TITLE
[dev-hilt] Provide an example of Service injection

### ISSUE THREAD

**Issue by peterLaurence** [android/architecture-samples#741]
As per the documentation, injection inside a Service should be as simple as:

```kotlin
@AndroidEntryPoint
class LocationService : Service() {
    @Inject lateinit var someImpl: SomeInterface
}
```

However, that same `SomeInterface` is already injected into various components such as activity and fragments.
The corresponding Hilt module is:

```kotlin
@Module
@InstallIn(ApplicationComponent::class)
object AppModule {
    @Singleton
    @Provides
    fun bindSomeInterface(): SomeInterface = SomeImpl()
}
```

It works great. However injection isn't done for services (I get `UninitializedPropertyAccessException`).
So I tried to create another module, using this time `@InstallIn(ServiceComponent::class)` - but no luck (there's an error telling that `SomeInterface` is already bound).
I'm running out of options. Any idea?

**Comment by cmpeguerog** [comment]
Im facing the same issue when try to inject a dependency inside a `BroadcastReceiver` and no example is provided.

**Comment by peterLaurence** [comment]
@manuelvicnt Do you have an idea about this issue?

**Comment by cmpeguerog** [comment]
@peterLaurence Can you share the code you are using becuase i tested you approach and it works fine. I share with you my code.

**Sample Code:** 

```
interface Interface {
    fun run(message: String)
}
```

```
class InterfaceImpl: Interface {
    override fun run(message: String) {
        Log.d(InterfaceImpl::class.java.simpleName, "run: $message")
    }
}
```
```
@Module
@InstallIn(ApplicationComponent::class)
object Module {

    @Provides
    @Singleton
    fun provideInterfaceImplementation(): Interface = InterfaceImpl()
}
```
```
@AndroidEntryPoint
class HiltService: Service() {

    override fun onBind(intent: Intent?): IBinder? = null

    @Inject
    lateinit var interfaceImpl: Interface

    override fun onCreate() {
        super.onCreate()

        interfaceImpl.run("Invoke from Service.")
    }
}
```
```
@HiltAndroidApp
class App: Application() {

    override fun onCreate() {
        super.onCreate()
        Log.d(App::class.simpleName, "onCreate: Created class")
    }
}
```

```
@AndroidEntryPoint
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        startService(Intent(this, HiltService::class.java))
    }
}
```
```
<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:roundIcon="@mipmap/ic_launcher_round"
    android:supportsRtl="true"
    android:theme="@style/AppTheme"
    android:name=".App">
    <activity android:name=".MainActivity">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

    <service android:name=".HiltService"/>
</application>
```
**Output:** 

`06-20 15:21:31.498 4919-4919/com.test.myapplication D/InterfaceImpl: run: Invoke from Service.`

**Comment by peterLaurence** [comment]
@cmpeguerog Thank you so much, I finally found my mistake. I had the same code as you, except for one little difference:

*In my service, I was trying to access the injected object _before_ `super.onCreate()`*

It's so easy to make this mistake.. so for people reading this: hilt injection happens during `super.onCreate()` of your service.
