### ISSUE TITLE
[Feature Request] Implementation new rebuild app architecture approach

### ISSUE THREAD

**Issue by underwindfall** [android/architecture-samples#812]
@JoseAlcerreca  Based on the latest blog written by android official teams, it looks like that Google is re-considering adding new `architecture` to help the community to have an architecture to allow the app more to scale, improve quality and robustness...

I think it'll be great to add this practice into Blueprints.

The blog link is here
https://android-developers.googleblog.com/2021/12/rebuilding-our-guide-to-app-architecture.html

**Comment by tunjid** [comment]
This is done.
