### ISSUE TITLE
cc nnnnnnnnnnnnnnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm         

### ISSUE THREAD

**Issue by kmnaseef** [android/architecture-samples#852]

**Comment by kongnanlive** [comment]
@kmnaseef you brought shame to india

**Comment by kmnaseef** [comment]
I don't know how to apologize.  Really really sorry. It was a mistake
without my knowledge. please tell me a way to delete this..
