### ISSUE TITLE
Request/Complaint

### ISSUE THREAD

**Issue by DoozyDoz** [android/architecture-samples#853]
### Description
 - I cannot find a good example of an actual `remoteDatasource` in any of the branches, It would be nice to have one based on the commonly used HTTP clients (OKHttp, retrofit...), the `fakeRemoteDatasource` in the mock directory is so different from what an actual remote data source would be like and therefore hard to maneuver
 - The docs mention the use of a `uiState` class when updating the UI but there is still no example here

**Comment by tunjid** [comment]
@DoozyDoz hello! Does https://github.com/android/nowinandroid have what you need? Specifically https://github.com/android/nowinandroid/blob/main/core-network/src/main/java/com/google/samples/apps/nowinandroid/core/network/retrofit/RetrofitNiaNetwork.kt

**Comment by DoozyDoz** [comment]
Thanks @tunjid ,  Exactly what I was looking for 😂👌👌👌
