### ISSUE TITLE
Calling the architecture MVP is misleading when there's no M

### ISSUE THREAD

**Issue by farmazon3000** [android/architecture-samples#91]
I'm constantly running into this issue with many examples and I'll report my concerns here. You call the architecture MVP which is misleading when there's no M - check this picture (taken from https://github.com/googlesamples/android-architecture/tree/todo-mvp/):
https://github.com/googlesamples/android-architecture/wiki/images/mvp.png
... so if there's M, then please mark it on that picture.

**Comment by jydimir** [comment]
@farmazon3000 Great remark. For those who had experince with MVP(MVC) it's obvious where M is. But for "MVP(MVC) beginners" isn't. So would be great to add clarificaion in that image.

**Comment by farmazon3000** [comment]
`For those who had experince with MVP(MVC)` Yes and I think repos like this are not for those who have experience but rather for `MVP(MVC) beginners`.

**Comment by tunjid** [comment]
Closing as obsolete.
