### ISSUE TITLE
Database calls on main UI thread

### ISSUE THREAD

**Issue by ghost** [android/architecture-samples#94]
Shouldn't the local database calls be handled off of the UI thread? If you create a few tasks with large descriptions the app hangs, even showing unresponsive messages.

**Comment by JoseAlcerreca** [comment]
Yes. The MVP sample only executes the `remotedatasource.getTasks()` on a different thread. Samples like MVP-Clean get off the main thread asap. This should be documented.

**Comment by ChenQingZhen** [comment]
I found sample like MVP-Dagger also call database in UI Thread

**Comment by tunjid** [comment]
Closing as obsolete.
