### ISSUE TITLE
Dagger Hilt Kapt to Ksp

### ISSUE THREAD

**Issue by binayshaw7777** [android/architecture-samples#975]
This will be a minor change in the gradle files.

**Comment by dturner** [comment]
You did not sign the CLA so we cannot accept your pull request.

**Comment by binayshaw7777** [comment]
Is this what you meant? @dturner 
I already signed it. Am I missing something here?
![Screenshot_2023-10-19-22-31-12-463_com android chrome](https://github.com/android/architecture-samples/assets/62587060/97f179ae-ebbb-4f02-a406-6f1e81f44d63)

**Comment by dturner** [comment]
Ah ok it seems like you deleted the branch which the PR is based on so that's why the PR was closed. You must have signed the CLA after the PR was closed.
